name: flag-gems-test-on-metax

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.py'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.hpp'
      - '**.cc'
      - 'CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.mk'
      - 'Makefile'

jobs:
  op-test-on-metax:
    runs-on: metax
    concurrency:
      group: op-test-on-metax-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FlagGems reduction ops on metax
        shell: bash
        run: |
          source tools/run_command.sh
          # FIXME(metax): error: invalid pointer element type: '!tt.ptr<i64>'
          # GEMS_VENDOR=metax run_command pytest -s tests/test_reduction_ops.py && \
          # FIXME(metax): triton.compiler.errors.CompilationError
          # GEMS_VENDOR=metax run_command pytest -s tests/test_general_reduction_ops.py && \
          # FIXME(metax): Killed
          # GEMS_VENDOR=metax run_command pytest -s tests/test_norm_ops.py

      - name: FlagGems pointwise ops on metax
        shell: bash
        run: |
          ### set private mem out of docker in case OOM
          # modprobe -r metax
          # modprobe metax pri_mem_sz=40

          source tools/run_command.sh
          GEMS_VENDOR=metax run_command pytest -s tests/test_pointwise_dynamic.py && \
          GEMS_VENDOR=metax run_command pytest -s tests/test_unary_pointwise_ops.py && \
          # FIXME(metax): Fix AssertionError for this test
          # GEMS_VENDOR=metax run_command pytest -s tests/test_binary_pointwise_ops.py && \
          GEMS_VENDOR=metax run_command pytest -s tests/test_pointwise_type_promotion.py && \
          GEMS_VENDOR=metax run_command pytest -s tests/test_tensor_constructor_ops.py

      - name: FlagGems blas ops on metax
        shell: bash
        run: |
          source tools/run_command.sh
          GEMS_VENDOR=metax run_command pytest -s tests/test_blas_ops.py
          # FIXME(metax): TypeError: 'list' object is not callable
          # GEMS_VENDOR=metax run_command pytest -s tests/test_attention_ops.py

      - name: FlagGems special ops on metax
        shell: bash
        run: |
          source tools/run_command.sh
          # FIXME(metax): Fix core dump for this test
          # GEMS_VENDOR=metax run_command pytest -s tests/test_special_ops.py && \
          GEMS_VENDOR=metax run_command pytest -s tests/test_distribution_ops.py

      - name: FlagGems utils on metax
        shell: bash
        run: |
          source tools/run_command.sh
          GEMS_VENDOR=metax run_command pytest -s tests/test_libentry.py && \
          GEMS_VENDOR=metax run_command pytest -s tests/test_shape_utils.py && \
          GEMS_VENDOR=metax run_command pytest -s tests/test_tensor_wrapper.py

      - name: FlagGems examples on metax
        shell: bash
        run: |
          source tools/run_command.sh
          # FIXME(metax): This test will fail for maybe bad internet connection
          # GEMS_VENDOR=metax run_command pytest -s examples/model_bert_test.py
